development:
  adapter: postgresql
  encoding: unicode
  database: r2013-03-12-flirt_development
  host: localhost
  pool: 5
  username: ronjones
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: r2013-03-12-flirt_test
  host: localhost
  pool: 5
  username: ronjones
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: r2013-03-12-flirt_production
  pool: 5
  host: localhost
  username: ronjones
  password:
