
development:
  adapter: postgresql
  encoding: unicode
  database: r2013-03-19-photo-albm_development
  host: localhost
  pool: 5
  username: ronjones
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: r2013-03-19-photo-albm_test
  host: localhost
  pool: 5
  username: ronjones
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: r2013-03-19-photo-albm_production
  host: localhost
  pool: 5
  username: ronjones
  password:
